 storages:
   - name: main
     plugin: fs
     config:
       directory: /var/lib/yandex/unified_agent/main
       max_partition_size: 100mb
       max_segment_size: 10mb

 channels:
   - name: cloud_monitoring
     channel:
       pipe:
         - storage_ref:
             name: main
         - filter:
             plugin: filter_metrics
             config:
               match: "{name=sys.memory.MemFree}"
       output:
         plugin: yc_metrics
         config:
           folder_id: b1gfhf2fs6hrugsk9asj
           iam:
             cloud_meta: {}

 routes:
   - input:
       plugin: linux_metrics
       config:
         namespace: sys
         poll_period: 1s
         resources:
           cpu: basic
           memory: basic
           io: basic
           network: basic
           kernel: basic
           storage: basic
     channel:
       channel_ref:
         name: cloud_monitoring